# Generated by Django 5.2.9 on 2026-01-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center_administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='centeradministratorprofile',
            table='center_administrator',
        ),
    ]
