# Generated by Django 5.2.9 on 2026-01-02 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoguiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_personal', models.TextField(blank=True)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('url_profile_picture', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('point_accumulated', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
