# Generated by Django 5.2.9 on 2026-01-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yoguiprofile',
            name='is_yogui',
            field=models.BooleanField(default=True),
        ),
    ]
