# Generated by Django 5.2.9 on 2026-01-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogui', '0002_yoguiprofile_is_yogui'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yoguiprofile',
            table='yogui_profile',
        ),
    ]
