# Generated by Django 5.2.9 on 2026-01-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogui', '0003_alter_yoguiprofile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yoguiprofile',
            old_name='experience_level',
            new_name='info_message',
        ),
    ]
