# Generated by Django 5.2.9 on 2026-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructorprofile',
            old_name='rating',
            new_name='qualification',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_instructor',
            field=models.BooleanField(default=True),
        ),
    ]
