# Generated by Django 5.2.9 on 2026-01-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_rename_rating_instructorprofile_qualification_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructorprofile',
            table='instructor_profile',
        ),
    ]
