# Generated by Django 5.2.9 on 2026-01-02 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userYC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useryogacenter',
            name='datatime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
