# Generated by Django 5.2.9 on 2026-01-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userYC', '0002_useryogacenter_datatime_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useryogacenter',
            options={},
        ),
        migrations.AlterModelTable(
            name='useryogacenter',
            table='user_yoga_center',
        ),
    ]
